# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: terminal.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List, Optional

import betterproto


@dataclass
class ClientMessage(betterproto.Message):
    auth_request: "AuthRequest" = betterproto.message_field(1, group="payload")
    register_host: "RegisterHostRequest" = betterproto.message_field(2, group="payload")
    pty_input: "PtyInput" = betterproto.message_field(3, group="payload")
    pty_resize: "PtyResize" = betterproto.message_field(4, group="payload")
    toggle_screen: "ToggleScreenRequest" = betterproto.message_field(5, group="payload")
    toggle_admin: "ToggleAdminRequest" = betterproto.message_field(6, group="payload")
    client_id: str = betterproto.string_field(10)


@dataclass
class ServerMessage(betterproto.Message):
    auth_response: "AuthResponse" = betterproto.message_field(1, group="payload")
    register_host_response: "RegisterHostResponse" = betterproto.message_field(
        2, group="payload"
    )
    pty_output: "PtyOutput" = betterproto.message_field(3, group="payload")
    pty_exit: "PtyExit" = betterproto.message_field(4, group="payload")
    system_message: "SystemMessage" = betterproto.message_field(5, group="payload")
    error_message: "ErrorMessage" = betterproto.message_field(6, group="payload")
    screen_frame: "ScreenFrame" = betterproto.message_field(7, group="payload")


@dataclass
class HostMessage(betterproto.Message):
    auth_request: "AuthRequest" = betterproto.message_field(1, group="payload")
    register_host: "RegisterHostRequest" = betterproto.message_field(2, group="payload")
    pty_output: "PtyOutput" = betterproto.message_field(3, group="payload")
    pty_exit: "PtyExit" = betterproto.message_field(4, group="payload")
    screen_frame: "ScreenFrame" = betterproto.message_field(5, group="payload")
    capabilities: "HostCapabilities" = betterproto.message_field(6, group="payload")


@dataclass
class AuthRequest(betterproto.Message):
    host_id: str = betterproto.string_field(1)
    token: str = betterproto.string_field(2)


@dataclass
class AuthResponse(betterproto.Message):
    ok: bool = betterproto.bool_field(1)
    error: str = betterproto.string_field(2)


@dataclass
class RegisterHostRequest(betterproto.Message):
    host_id: str = betterproto.string_field(1)
    password: str = betterproto.string_field(2)
    run_as_admin: bool = betterproto.bool_field(3)


@dataclass
class RegisterHostResponse(betterproto.Message):
    ok: bool = betterproto.bool_field(1)
    token: str = betterproto.string_field(2)
    error: str = betterproto.string_field(3)
    is_admin: bool = betterproto.bool_field(4)


@dataclass
class PtyInput(betterproto.Message):
    data: str = betterproto.string_field(1)


@dataclass
class PtyResize(betterproto.Message):
    cols: int = betterproto.uint32_field(1)
    rows: int = betterproto.uint32_field(2)


@dataclass
class PtyOutput(betterproto.Message):
    data: str = betterproto.string_field(1)
    client_id: str = betterproto.string_field(2)


@dataclass
class PtyExit(betterproto.Message):
    code: int = betterproto.int32_field(1)
    client_id: str = betterproto.string_field(2)


@dataclass
class SystemMessage(betterproto.Message):
    message: str = betterproto.string_field(1)


@dataclass
class ErrorMessage(betterproto.Message):
    message: str = betterproto.string_field(1)


@dataclass
class ScreenFrame(betterproto.Message):
    data: bytes = betterproto.bytes_field(1)
    width: int = betterproto.uint32_field(2)
    height: int = betterproto.uint32_field(3)


@dataclass
class ToggleScreenRequest(betterproto.Message):
    enabled: bool = betterproto.bool_field(1)


@dataclass
class ToggleAdminRequest(betterproto.Message):
    enabled: bool = betterproto.bool_field(1)


@dataclass
class HostCapabilities(betterproto.Message):
    supports_screen_share: bool = betterproto.bool_field(1)
    supports_admin_mode: bool = betterproto.bool_field(2)
    is_admin: bool = betterproto.bool_field(3)
