name: Build Mobile App (Android)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'mobileapp/**'
      - 'packages/protocol/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'mobileapp/package-lock.json'

      - name: Install dependencies
        working-directory: mobileapp
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Prebuild Native Files
        working-directory: mobileapp
        run: npx expo prebuild --platform android --no-install

      - name: Build Android Debug APK
        working-directory: mobileapp/android
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terminal-tool-debug-apk
          path: mobileapp/android/app/build/outputs/apk/debug/app-debug.apk
